name: form_builder_validators
description: Form Builder Validators set of validators for FlutterFormBuilder. Provides common validators and a way to make your own.
version: 9.2.0
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_validators
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_validators/issues
homepage: https://github.com/flutter-form-builder-ecosystem
topics:
  - form
  - validator
funding:
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  generate: true
